name: luneta
version: "0.7.4"
summary: Terminal fuzzy finder
description: |
  Luneta is an interactive filter that can be easily composed within any script.

base: core18
grade: stable
confinement: strict
license: GPL-2.0

apps:
  luneta:
    command: luneta

parts:
  luneta:
    source: https://github.com/fbeline/luneta
    source-type: git
    source-branch: master
    plugin: dump
    build-snaps:
      - dub
      - ldc2
    build-packages:
      - libncursesw5-dev
    stage-packages:
      - libncursesw5
    override-build: |
      snapcraftctl build
      dub build -b release --compiler ldc2
      mv ./luneta $SNAPCRAFT_PART_INSTALL/

architectures:
  - build-on: amd64
